trajectory_planner:
  ros__parameters:
    odom_topic: "/odom"
    map_topic: "/map"
    scan_topic: "/scan"
    initial_pose_topic: "/initialpose"
    # centerline: "$(find-pkg-share path_planning)/config/sim/sim_config.yaml"
trajectory_follower:
  ros__parameters:
    # odom_topic: "/pf/pose/odom"
    odom_topic: "/odom"
    drive_topic: "/drive"
